# Generated by Django 6.0.4 on 2026-05-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Kitob nomi')),
                ('author', models.CharField(db_index=True, max_length=150, verbose_name='Muallif')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('genre', models.CharField(db_index=True, max_length=100, verbose_name='Janr')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Mavjud nusxalar')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['-created_at'],
            },
        ),
    ]
