# Generated by Django 6.0.4 on 2026-05-05 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
    ]
