# Generated by Django 6.0.4 on 2026-05-05 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0003_remove_book_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('buy', 'Sotib olish'), ('rent', 'Ijaraga olish')], max_length=10, verbose_name='Tur')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="To'lov summasi")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.book', verbose_name='Kitob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
